### ISSUE TITLE
Secert Manager sub-task: new test case proves that the `vault` works as the secret manager backend.

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#10222]
### Description

This task is a sub-requirement of [8319](https://github.com/apache/apisix/issues/8319) and is used to independently verify the `vault` as the backend of the Secert manager. 

# Define the Data Range That Secret Manager Can Protect

The following configuration is designed to obtain values from the secert manager, which is called referenceable.
- [ ] authentication plugin
   - [x] Basic-auth 's password
   - [x] Key-auth key
   - [x] ldap-auth user_dn 
   - [x] appid of Wolf-rbac
   - [x] Hmac-auth’s access_key and secret_key
   - [x] Jwt-auth secret
   - [ ] client_secret of authz-keycloak (need test case ( work in progress
   - [ ] client_secret of authz-casdoor (need test case
   - [ ] client_secret of openid-connect (need test case
   - [ ] The RBAC configuration file information of authz-casbin requires secondary confirmation.
- [ ] logger plugin
   - [ ]  http-logger: auth_header (option)
   - [ ] tcp-logger: tls_options(option)
   - [ ] kafka-logger: brokers.sasl_config.user, brokers.sasl_config.password, key(option) of 
   - [ ] rocketmq-logger: access_key, secret_key of 
   - [ ] clickhouse-logger: user, password
   - [ ] error-log-logger: clickhouse.user, clickhouse.password, 
   - [ ] error-log-logger: kafka.brokers.sasl_config.user, kafka.brokers.sasl_config.password, kafka.key
   - [ ] sls-logger: access_key_id, access_key_secret
   - [ ] google-cloud-logging: auth_config.private_key
   - [ ]  loggly: customer_token
   - [ ] elasticsearch-logger: auth.password
   - [ ] tencent-cloud-cls: secret_id, secret_key
- [ ] Other plugin
  - [ ] kafka-proxy: sasl.password
- [ ] Security plugin
  - [ ] csrf: key

**Comment by Sn0rt** [comment]
PR list:
authz-keycloak https://github.com/apache/apisix/pull/10291
