### ISSUE TITLE
Billboard: all chaos test to do ( welcome new ideas!😆)

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#3449]
### Background
See #2757

### Todo List
**Architecture**
- [x] Build github actions that running APISIX on k8s, and deploy chaos on APISIX with chaos mesh.

**Chaos Test**
- [x] kill all etcd, see if route visit still works (#3404)
- [ ] restart etcd and see how it works (resend from memory to etcd)
- [ ] give low&high network delay between apisix and etcd, see if it works
- [ ] cpu/memory/disk stressed out and see how apisix works

**Welcome more ideas!😆**

**Comment by tokers** [comment]
@Yiyiyimu Have you tried to make the network partition for the etcd cluster? To see the behavior of APISIX.

**Comment by Yiyiyimu** [comment]
> @Yiyiyimu Have you tried to make the network partition for the etcd cluster? To see the behavior of APISIX.

Thanks for the suggestion!! Added to todo and I'll try it later

**Comment by idbeta** [comment]
two ideas

1. kill one or two pods of etcd cluster , then check CRUD for routes, and then start etcd again，check CRUD for routes again.
2. when the network connected to etcd is relatively stuck, such as serious packet loss, create 1000 normal routes and check whether the routes are accessed.

**Comment by Yiyiyimu** [comment]
Hi @idbeta Thanks for the suggestions! The second one is great, but I failed to get what we could benefit from the first idea. Could you explain a little more

**Comment by idbeta** [comment]
> Hi @idbeta Thanks for the suggestions! The second one is great, but I failed to get what we could benefit from the first idea. Could you explain a little more

the current case is kill all etcd, I think should test the situation where some etcd instances are down.
the idea comes from:

> 我etcd是个集群，但是我宕一台etcd好像apisix重启就报错, 宕的是 Leader

**Comment by Yiyiyimu** [comment]
Hi @idbeta thx for explaination! Added to todo and I'll test it later. Is it from certain issue so I could have some context to reproduce

**Comment by hnlq715** [comment]
@Yiyiyimu  delete all etcd data to see apisix's behavior.

**Comment by tzssangglass** [comment]
update data directly in etcd with high frequency
update the same route at high frequency

**Comment by Yiyiyimu** [comment]
Many thanks @hnlq715 @tzssangglass !!

**Comment by moonming** [comment]
I need to remind that we test the stability of apisix, not etcd.

We need to look at this issue from a higher perspective.

**Comment by moonming** [comment]
@Yiyiyimu I think you should look at the stability of the apisix cluster from the perspective of the overall architecture, and find out the weaknesses of the system one by one.  Instead of randomly shoot.

**Comment by moonming** [comment]
1. Part or all of the dp and cp networks are disconnected 2. The cp node is down randomly 3. The dp node is attacked by ddos ​​4. The disk of the dp node is full 5. The sykwalking server is down 6. The oauth 2.0 server is down 7. Kafka server ia down etc.

**Comment by Yiyiyimu** [comment]
@moonming Thanks for the suggestions. That would be so helpful! I'll focus on architecture weakness first and then do some random shoots
